# Generated by Django 4.1.7 on 2023-04-11 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tournament', '0005_alter_team_user_alter_tournamentobject_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentobject',
            name='name',
            field=models.CharField(default='My Tournament', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentobject',
            name='num_teams',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='tournamentobject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourney', to=settings.AUTH_USER_MODEL),
        ),
    ]
